[workspace]
members = ["crates/blerp", "crates/volt"]
resolver = "2"

# Compile time and runtime optimizations
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"