[package]
name = "blerp"
version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
cpal = { workspace = true }
itertools = { workspace = true }
nom = "7.1.3"
nom_locate = "4.2.0"
num = "0.4.3"
thiserror = "2.0.9"
