[package]
name = "blerp"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15.3"
itertools = "0.14.0"
nom = "7.1.3"
nom-bufreader = "0.2.0"
nom_locate = "4.2.0"
num = "0.4.3"
thiserror = "2.0.9"
