name: Rust
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Cache target directory
      uses: actions/cache@v4.2.0
      with:
        path: target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      name: Install dependencies
      run: sudo apt install -y libasound2-dev
    - name: Build
      run: cargo build -r
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: target/release/volt*
        name: volt-${{ matrix.os }}
